In [2]:
#사이킷런 버전 확인하기!
import sklearn
print(sklearn.__version__)

0.24.1


In [5]:
import numpy as np

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
list1 = [1,2,3]

In [13]:
array1=np.array([1,2,3])

#코드의 앞으로 가려면 HOME버튼 뒤로 가려먼 END버튼을 사용해보자!

#array의 type을 확인하는 코드
print(type(array1))

#list1의 type을 확인하는 코드
print(type(list1))

#array의 형태를 확인하는 코드
print(array1.shape)

#array의 차원을 확인하는 코드
print(array1.ndim)

<class 'numpy.ndarray'>
<class 'list'>
(3,)
1


In [17]:
array2 = np.array([[[1,2,3]],[[5,6,7]]])

#형태가 (2,1,3)으로 나오는 이유는? :: 뒤에서부터 세기 때문에!
#요소가 3개인 덩어리가 크게는 한개가 있는데 그 안에 두개의 덩어리가 있구나!
print(array2.shape)
#그리고 차원이 3차원인 이유는 []이 꺽쇠 표시가 3개 있기 때문
print(array2.ndim)

(2, 1, 3)
3


## array에서 형태와 차원을 파악하는 것은 매우 중요

> Array의 형태와 차원 연습해보기

In [19]:
array3 = np.array([[1,2,3]])
print(array3.shape)
#3개의 요소가 크게 한 덩어리!
print(array3.ndim)
#꺽쇠가 두개니까 2차원 이겠구나를 예상해보기

(1, 3)
2


In [21]:
array4 = np.array([1,2,3])
print(array4.shape)
#3개 요소가 끝이니까 (,3)으로 나오려나?
print(array4.ndim)
#꺽쇠가 하나니까 1차원이겠구나

(3,)
1


In [22]:
#결과는 X :: 튜플 형태는 무조건 뒤에 콤마가 있어야 한다
#(1,3) 이런식으로 결과값이 하나를 도출할 경우 (3,)으로 표현한다 *^^*

## (2,3,1) (2,1,3) (2,2,1,4) 스스로 만들어보기

In [39]:
array5 = np.array([[[1],[2],[3]],[[4],[5],[6]]])
print(array5.shape)
#요소 1개짜리 덩어리가 3개 그리고 그 3개짜리 덩어리가 2개! (2,3,1)
print(array5.ndim)
#꺽쇠가 3개니 3차원!

(2, 3, 1)
3


In [38]:
array6 = np.array([[['Jake','Finn','BubbleGum']],
                   [['Marceline','Bmo','Ice King']]])
print(array6.shape)
#요소 3개짜리 덩어리가 1개 그리고 그 1개짜리 덩어리가 2개! (2,1,3)
print(array6.ndim)
#꺽쇠가 3개니 3차원!

(2, 1, 3)
3


In [65]:
array7 = np.array([[[[1,2,3,4]],[[5,6,7,8]]],[[[9,10,11,12]],[[13,14,15,16]]]])
print(array7.shape)
#요소 4개짜리 덩어리가 1개씩 있는게 2 덩어리 그리고 그 덩어리가 2개! (2,2,1,4)
print(array7.ndim)
#꺽쇠가 4개니 4차원!
print('Array연산: \n')
print(array7*2)

(2, 2, 1, 4)
4
Array연산: 

[[[[ 2  4  6  8]]

  [[10 12 14 16]]]


 [[[18 20 22 24]]

  [[26 28 30 32]]]]


## array를 reshape 하기

In [69]:
import numpy as np
sequence_array = np.arange(10) 
#a range :: not arrange 정렬하는게 아니라 범위!
#그래서 1부터 10까지의 범위를 출력함 (python은 0부터 시작하고 10까지 할 경우 그 전인 9까지 출력)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape, sequence_array.ndim)
#sequence_array의 타입은 int(정수형) , 요소는 10개, 1차원

[0 1 2 3 4 5 6 7 8 9]
int32 (10,) 1


In [74]:
#1차원 array를 2차원 array로 바꾸기
sequence_array2 = sequence_array.reshape(2,5)
print(sequence_array2)
print(sequence_array2.ndim)
#요소 5개씩 2덩어리

sequence_array3 = sequence_array.reshape(10,1)
print(sequence_array3)
print(sequence_array3.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
2


## ndrray를 편리하게 생성하기 - arange, zeros, ones

In [75]:
range(10)

range(0, 10)

In [77]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [94]:
array8 = np.arange(8)

## numpy.reshape()를 이용한 차원 추가

In [122]:
#1차원 array -> 2차원 array
array_rev2 = array8.reshape(4,2)
print(array_rev2)
print('array_rev2의 차원: ',array_rev2.ndim)

#2차원 array -> 3차원 array
array_rev3 = array_rev2.reshape(2,2,2)
print(array_rev3)
print('array_rev3의 차원: ',array_rev3.ndim)


rray_rev4 = array_rev3.reshape(1,2,2,2)
print(array_rev4)
print('array_rev4의 차원: ',array_rev4.ndim)

#3차원 array -> 2차원 array (어떠한 -값도 오케이!)
array_rev2d = array_rev3.reshape(-999,2) 
print(array_rev2d)
print(array_rev2d.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
array_rev2의 차원:  2
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array_rev3의 차원:  3
[[[[0 1]
   [2 3]]

  [[4 5]
   [6 7]]]]
array_rev4의 차원:  4
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
2


In [126]:
#tolist()함수는 list로 만드는 함수
array_1 = np.arange(8)
array3d = array_1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())
array3d

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])